//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoteAppLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RemoteAppLauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE [PersistedFileItem] ADD CONSTRAINT [PK_PersistedFileItem] PRIMARY KEY ([Id]);.
        /// </summary>
        internal static string PersistedItemCreateConstraint {
            get {
                return ResourceManager.GetString("PersistedItemCreateConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE UNIQUE INDEX [UQ__PersistedFileItem__0000000000000012] ON [PersistedFileItem] ([Id] ASC);.
        /// </summary>
        internal static string PersistedItemCreateIndex {
            get {
                return ResourceManager.GetString("PersistedItemCreateIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [PersistedFileItem] (
        ///  [Id] nvarchar(455) NOT NULL
        ///, [Name] nvarchar(100) NOT NULL
        ///, [Path] nvarchar(455) NOT NULL
        ///, [Directory] ntext NOT NULL
        ///, [Pinned] bit NOT NULL
        ///, [Accesses] bigint NOT NULL
        ///);.
        /// </summary>
        internal static string PersistedItemTableCreate {
            get {
                return ResourceManager.GetString("PersistedItemTableCreate", resourceCulture);
            }
        }
    }
}
